package com.android.gandharvms.Inward_Truck_Security;

import androidx.activity.result.ActivityResultCallback;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.app.TimePickerDialog;
import android.content.Intent;
import android.content.SharedPreferences;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TimePicker;
import android.widget.Toast;

import com.android.gandharvms.FcmNotificationsSender;
import com.android.gandharvms.Inward_Truck;
import com.android.gandharvms.R;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.storage.FirebaseStorage;
import com.google.firebase.storage.StorageReference;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;

public class Inward_Truck_Security extends AppCompatActivity {

    String [] items = {"Ton","Litre","KL","Kgs","pcs"};

    String [] items1 = {"Ton","Litre","KL","Kgs","pcs"};
    AutoCompleteTextView autoCompleteTextView;
    AutoCompleteTextView autoCompleteTextView1;
    ArrayAdapter<String> adapterItems;
    ArrayAdapter<String> adapterItems1;


    ActivityResultLauncher<String> launcher;
    EditText etintime,etserialnumber,etvehicalnumber,etsinvocieno,etsdate,etssupplier,etsmaterial,etsqty,etsuom,etsnetwt,etsuom2;
    ImageView img1,img2,img3,img4;
    Button wesubmit;
    Button view;
    FirebaseFirestore intrsdbroot;
    DatePickerDialog pickertr;
    TimePickerDialog tpicker;
    FirebaseStorage storage;
    Uri image1,image2,image3,image4;
    private SharedPreferences sharedPreferences;
    private int autoGeneratedNumber;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_inward_truck_security);

        //Send Notification to all
        FirebaseMessaging.getInstance().subscribeToTopic("all");

                                  // Uom work
        autoCompleteTextView= findViewById(R.id.etsuom);
        autoCompleteTextView1=findViewById(R.id.etsuom2);

        adapterItems = new ArrayAdapter<String>(this,R.layout.list_itemuom,items);
        adapterItems1 = new ArrayAdapter<String>(this,R.layout.in_tr_se_nwe_list,items1);

        autoCompleteTextView.setAdapter(adapterItems);
        autoCompleteTextView1.setAdapter(adapterItems1);

        // for Auto Genrated serial number
        sharedPreferences = getSharedPreferences("TruckSecurity", MODE_PRIVATE);
        autoCompleteTextView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                String items = parent.getItemAtPosition(position).toString();
                Toast.makeText(getApplicationContext(), "Item"+items, Toast.LENGTH_SHORT).show();
            }
        });
        autoCompleteTextView1.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                String items1 = parent.getItemAtPosition(position).toString();
                Toast.makeText(getApplicationContext(), "Item"+items1, Toast.LENGTH_SHORT).show();
            }
        });


        etintime= (EditText) findViewById(R.id.etintime);
        etserialnumber= (EditText) findViewById(R.id.etserialnumber);
        etvehicalnumber= (EditText) findViewById(R.id.etvehicalnumber);
        etsinvocieno=(EditText) findViewById(R.id.etsinvocieno);
        etsdate=(EditText) findViewById(R.id.etsdate);
        etssupplier=(EditText) findViewById(R.id.etssupplier);
        etsmaterial=(EditText) findViewById(R.id.etsmaterial);
        etsqty=(EditText) findViewById(R.id.etsqty);
        etsuom=(EditText) findViewById(R.id.etsuom);
        etsnetwt=(EditText) findViewById(R.id.etsnetwt);
        etsuom2=(EditText) findViewById(R.id.etsuom2);

        img1=(ImageView)findViewById(R.id.intrtrlrco);
        img2=(ImageView)findViewById(R.id.intrdech);
        img3=(ImageView)findViewById(R.id.intrtain);
        img4=(ImageView)findViewById(R.id.intrewabi);

        storage = FirebaseStorage.getInstance();


      //for imgpicker
        img1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mGetContent.launch("image/*");
            }
        });
        img2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                m1GetContent.launch("image/*");
            }
        });
        img3.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                m2GetContent.launch("image/*");
            }
        });
        img4.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                m3GetContent.launch("image/*");
            }
        });


                                                    // listing button

        view= findViewById(R.id.viewdb);
        view.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(Inward_Truck_Security.this,Inward_Truck_Security_viewdata.class));
            }
        });








        etsdate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                final Calendar calendar = Calendar.getInstance();
                int day = calendar.get(Calendar.DAY_OF_MONTH);
                int month = calendar.get(Calendar.MONTH);
                int year = calendar.get(Calendar.YEAR);
                pickertr = new DatePickerDialog(Inward_Truck_Security.this, new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(DatePicker view, int year, int month, int dayOfMonth) {
                        etsdate.setText(dayOfMonth + "/" + (month +1 ) + "/" + year);
                    }
                } ,year,month,day);
                pickertr.show();
            }
        });

        etintime.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
             Calendar calendar = Calendar.getInstance();
             int hours = calendar.get(Calendar.HOUR_OF_DAY);
             int mins = calendar.get(Calendar.MINUTE);


             tpicker = new TimePickerDialog(Inward_Truck_Security.this, new TimePickerDialog.OnTimeSetListener() {
                 @Override
                 public void onTimeSet(TimePicker view, int hourOfDay, int minute) {
                   Calendar c = Calendar.getInstance();
                   c.set(Calendar.HOUR_OF_DAY,hourOfDay);
                   c.set(Calendar.MINUTE,minute);
                   etintime.setText(hourOfDay +":"+ minute );
                 }
             },hours,mins,false);
             tpicker.show();
            }
        });




        wesubmit = (Button)findViewById(R.id.wesubmit);
        intrsdbroot=FirebaseFirestore.getInstance();



        wesubmit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                trsedata();
                uploadimg();
            }
        });

        if (sharedPreferences != null) {
            autoGeneratedNumber = sharedPreferences.getInt("autoGeneratedNumber", 1);
            String autoGeneratedNumberString = String.format("%03d", autoGeneratedNumber);
            // Create the serial number
            String serialNumber = "I" + GetYear() + getMonth() + getDay() + autoGeneratedNumberString;
            // Set the serial number in the EditText
            etserialnumber.setText(serialNumber);
            // Increment and store the auto-generated number for the next vehicle

        } else {
            // Handle the case where sharedPreferences is null
            // This might involve displaying an error message or taking appropriate action
            Log.e("MainActivity", "SharedPreferences is null");
        }


    }
    private String GetYear() {
        SimpleDateFormat yearFormat = new SimpleDateFormat("yy", Locale.getDefault());
        return yearToLetter(yearFormat.format(new Date()));
    }

    private String getMonth() {
        SimpleDateFormat monthFormat = new SimpleDateFormat("MM", Locale.getDefault());
        return monthToLetter(monthFormat.format(new Date()));
    }

    private String getDay() {
        SimpleDateFormat dayFormat = new SimpleDateFormat("dd", Locale.getDefault());
        return dayFormat.format(new Date());
    }

    private String monthToLetter(String month) {
        switch (month) {
            case "01":
                return "A";
            case "02":
                return "B";
            case "03":
                return "C";
            case "04":
                return "D";
            case "05":
                return "E";
            case "06":
                return "F";
            case "07":
                return "G";
            case "08":
                return "H";
            case "09":
                return "I";
            case "10":
                return "J";
            case "11":
                return "K";
            case "12":
                return "L";
            default:
                return null; // Default to January (A) if month is not recognized
        }
    }
    private String yearToLetter(String month) {
        switch (month) {
            case "23":
                return "A";
            case "24":
                return "B";
            case "25":
                return "C";
            case "26":
                return "D";
            case "28":
                return "E";
            case "29":
                return "F";
            case "30":
                return "G";
            case "31":
                return "H";
            case "32":
                return "I";
            case "33":
                return "J";
            case "34":
                return "K";
            case "35":
                return "L";
            case "36":
                return "M";
            case "37":
                return "N";
            case "38":
                return "O";
            case "39":
                return "P";
            case "40":
                return "Q";
            case "41":
                return "R";
            case "42":
                return "S";
            case "43":
                return "T";
            case "44":
                return "U";
            case "45":
                return "V";
            case "46":
                return "W";
            case "47":
                return "X";
            case "48":
                return "Y";
            case "49":
                return "Z";
            default:
                return null;
            // Default to January (A) if month is not recognized
        }
    }

    //img

    ActivityResultLauncher<String> mGetContent = registerForActivityResult(new ActivityResultContracts.GetContent(),

            new ActivityResultCallback<Uri>() {
                @Override
                public void onActivityResult(Uri result) {

                    if (result !=  null){
                        img1.setImageURI(result);
                        image1=result;

                    }
                }
            });

    ActivityResultLauncher<String> m1GetContent = registerForActivityResult(new ActivityResultContracts.GetContent(),
            new ActivityResultCallback<Uri>() {
                @Override
                public void onActivityResult(Uri result) {
                    if (result != null){
                        img2.setImageURI(result);
                    }

                }
            });
    ActivityResultLauncher<String> m2GetContent = registerForActivityResult(new ActivityResultContracts.GetContent(),
            new ActivityResultCallback<Uri>() {
                @Override
                public void onActivityResult(Uri result) {
                    if (result != null){
                        img3.setImageURI(result);
                    }

                }
            });
    ActivityResultLauncher<String> m3GetContent = registerForActivityResult(new ActivityResultContracts.GetContent(),
            new ActivityResultCallback<Uri>() {
                @Override
                public void onActivityResult(Uri result) {
                    if (result != null){
                        img4.setImageURI(result);
                    }

                }
            });


    public void makeNotification(){
        FcmNotificationsSender notificationsSender = new FcmNotificationsSender("/topics/all",
                "Security Process Done..!",
                "Weighment Can Start there Work",
                getApplicationContext(), Inward_Truck_Security.this);
        notificationsSender.SendNotifications();
    }

    public void trsedata(){

        String intime =  etintime.getText().toString().trim();
        String serialnumber = etserialnumber.getText().toString().trim();
        String vehicalnumber = etvehicalnumber.getText().toString().trim();
        String invoiceno =  etsinvocieno.getText().toString().trim();
        String date = etsdate.getText().toString().trim();
        String supplier = etssupplier.getText().toString().trim();
        String material = etsmaterial.getText().toString().trim();
        String qty = etsqty.getText().toString().trim();
        String uom = etsuom.getText().toString().trim();
        String netwt = etsnetwt.getText().toString().trim();
        String uom2 = etsuom2.getText().toString().trim();

        if (intime.isEmpty()|| serialnumber.isEmpty()|| vehicalnumber.isEmpty()|| invoiceno.isEmpty()|| date.isEmpty()|| supplier.isEmpty()|| material.isEmpty()
           || qty.isEmpty()|| uom.isEmpty()|| netwt.isEmpty()|| uom2.isEmpty()){
            Toast.makeText(this, "All fields must be filled", Toast.LENGTH_SHORT).show();
        }
        else {

            Map<String,String> trseitems = new HashMap<>();
            trseitems.put("Intime",etintime.getText().toString().trim());
            trseitems.put("serialnumber",etserialnumber.getText().toString().trim());
            trseitems.put("VehicalNumber",etvehicalnumber.getText().toString().trim());
            trseitems.put("invoicenumber",etsinvocieno.getText().toString().trim());
            trseitems.put("date",etsdate.getText().toString().trim());
            trseitems.put("Supplier",etssupplier.getText().toString().trim());
            trseitems.put("Material",etsmaterial.getText().toString().trim());
            trseitems.put("Qty",etsqty.getText().toString().trim());
            trseitems.put("UOM",etsuom.getText().toString().trim());
            trseitems.put("etsnetweight",etsnetwt.getText().toString().trim());
            trseitems.put("UOM2",etsuom2.getText().toString().trim());

            intrsdbroot.collection("Inward Truck Security").add(trseitems)
                    .addOnCompleteListener(new OnCompleteListener<DocumentReference>() {
                        @Override
                        public void onComplete(@NonNull Task<DocumentReference> task) {
                            etintime.setText("");
                            etserialnumber.setText("");
                            etvehicalnumber.setText("");
                            etsinvocieno.setText("");
                            etsdate.setText("");
                            etssupplier.setText("");
                            etsmaterial.setText("");
                            etsqty.setText("");
                            etsuom.setText("");
                            etsnetwt.setText("");
                            etsuom2.setText("");

                            Toast.makeText(Inward_Truck_Security.this, "Data Inserted Successfully", Toast.LENGTH_SHORT).show();


                        }
                    });

            Intent intent= new Intent(this, Inward_Truck.class);
            startActivity(intent);
            makeNotification();
            // Auto Genrated serial number
            sharedPreferences.edit().putInt("autoGeneratedNumber", autoGeneratedNumber + 1).apply();
        }

    }

    public void uploadimg(){
        List<Uri> imageUris = new ArrayList<>();
      if (image1 != null ){
          imageUris.add(image1);
//          StorageReference reference = storage.getReference().child("image/*" + UUID.randomUUID().toString());
      }
      if (image2 != null){
          imageUris.add(image2);
      }
      if (image3 != null){
          imageUris.add(image3);
      }
      if (image4 != null){
          imageUris.add(image4);
      }

      StorageReference storageReference = storage.getReference();
      for (Uri imageuris : imageUris){
          String Transport_LR_Copy = "image1"+UUID.randomUUID().toString();
          String Delivery_Chllan = "image2"+UUID.randomUUID().toString();
          String Tax_Invoice = "image3"+UUID.randomUUID().toString();
          String E_Way_Bill = "image4"+UUID.randomUUID().toString();


          StorageReference imgref1 = storageReference.child("images1/"+ Transport_LR_Copy);
          StorageReference imgref2 = storageReference.child("images2/"+Delivery_Chllan);
          StorageReference imgref3 = storageReference.child("images3/"+Tax_Invoice);
          StorageReference imgref4 = storageReference.child("images4/"+E_Way_Bill);

          imgref1.putFile(imageuris)
                  .addOnSuccessListener(taskSnapshot -> {
                     imgref1.getDownloadUrl().addOnSuccessListener(uri -> {
                         String imageUrl = uri.toString();
                     });
                  }).addOnFailureListener(e -> {

                  });
          imgref2.putFile(imageuris)
                  .addOnSuccessListener(taskSnapshot -> {
                      imgref2.getDownloadUrl().addOnSuccessListener(uri -> {
                          String imageurl = uri.toString();
                      });
                  }).addOnFailureListener(e -> {

                  });
          imgref3.putFile(imageuris)
                  .addOnSuccessListener(taskSnapshot -> {
                      imgref3.getDownloadUrl().addOnSuccessListener(uri -> {
                          String imageurl = uri.toString();
                      });
                  }).addOnFailureListener(e -> {

                  });
          imgref4.putFile(imageuris)
                  .addOnSuccessListener(taskSnapshot -> {
                      imgref4.getDownloadUrl().addOnSuccessListener(uri -> {
                          String imageuri = uri.toString();
                      });
                  }).addOnFailureListener(e -> {

                  });


      }
    }


}